[providers]
java = "17"

[phases.build]
cmds = [
    "cd backend",
    "./mvnw clean package -DskipTests"
]

[phases.start]
cmd = "cd backend && java -Dserver.port=$PORT -jar target/*.jar"

[variables]
SPRING_PROFILES_ACTIVE = "production"
