[providers]
java = "17"

[phases.build]
cmds = [
    "cd backend",
    "chmod +x mvnw", 
    "./mvnw clean package -DskipTests"
]

[start]
cmd = "cd backend && java -Dserver.port=$PORT -jar target/*.jar"

[variables]
SPRING_PROFILES_ACTIVE = "production"
