[build]
# Build configuration for Railway
buildCommand = "cd backend && ./mvnw clean package -DskipTests"

[deploy]
# Deployment configuration
startCommand = "cd backend && java -jar target/*.jar"

[environments.production]
# Production environment variables
SPRING_PROFILES_ACTIVE = "production"
